spring:
  application:
    name: server02
server:
  port: 8762
eureka:
  client:
    service-url:
      zone1: http://localhost:8761/eureka/
      zone2: http://localhost:8762/eureka/
    region: region-east
    availability-zones:
      region-east: zone1,zone2
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    metadata-map:
      zone: zone2