spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            alllow-credentials: true
            allowed-origins: "http://localhost:9527"
            allowed-headers: "*"
            allowed-methods:
            - OPTIONS
            - GET
            - PUT
            - POST
            - DELETE
#              - "*"
server:
  port: 10010
eureka:
  client:
    service-url:
      zone1: http://localhost:8761/eureka
      zone2: http://localhost:8762/eureka
      zone3: http://localhost:8763/eureka
      zone4: http://localhost:8764/eureka
    availability-zones:
      region-east: zone1,zone2
      region-west: zone3,zone4
    region: region-east,region-west
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    metadata-map:
      zone: zone1,zone2,zone3,zone4
