spring:
  application:
    name: server04
server:
  port: 8764
eureka:
  client:
    service-url:
      zone3: http://localhost:8763/eureka/
      zone4: http://localhost:8764/eureka/
    region: region-west
    availability-zones:
      region-west: zone3,zone4
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    metadata-map:
      zone: zone4