server:
  port: 8090
spring:
  application:
    name: auth-service
eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    metadata-map:
      zone: zone1,zone2,zone3,zone4
  client:
    service-url:
      zone1: http://localhost:8761/eureka
      zone2: http://localhost:8762/eureka
      zone3: http://localhost:8763/eureka
      zone4: http://localhost:8764/eureka
    availability-zones:
      region-east: zone1,zone2
      region-west: zone3,zone4
    region: region-east,region-west